In [27]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

In [28]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [29]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [30]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [31]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emotion in unique_emotions:
    emotion_numbers[emotion] = i
    i += 1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [32]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [33]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [34]:
import string
def remove_punctuation(text):   
    return text.translate(str.maketrans('', '', string.punctuation))

In [35]:
df['text'] = df['text'].apply(remove_punctuation)

In [36]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [37]:
def remove_numbers(txt):
    new =""
    for i in txt:
        if not i.isdigit():
            new = new+i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [38]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [48]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [49]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [50]:
import nltk

In [51]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [52]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\aboyc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\aboyc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [53]:
stop_words = set(stopwords.words('english'))

In [54]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [55]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [56]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [57]:
df['text'] = df['text'].apply(remove)

In [58]:

df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [59]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

document = ["I love programming in Python", "Python is a great programming language", "I enjoy solving problems with Python"]   

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(document)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['enjoy' 'great' 'in' 'is' 'language' 'love' 'problems' 'programming'
 'python' 'solving' 'with']
[[0 0 1 0 0 1 0 1 1 0 0]
 [0 1 0 1 1 0 0 1 1 0 0]
 [1 0 0 0 0 0 1 0 1 1 1]]

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

document = ["I love programming in Python", "Python is a great programming language", "I enjoy solving problems with Python"]   

vectorizer = CountVectorizer(ngram_range=(3, 3))

X = vectorizer.fit_transform(document)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['enjoy solving problems' 'great programming language'
 'is great programming' 'love programming in' 'problems with python'
 'programming in python' 'python is great' 'solving problems with']
[[0 0 0 1 0 1 0 0]
 [0 1 1 0 0 0 1 0]
 [1 0 0 0 1 0 0 1]]

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = ["I love programming in Python", "Python is a great programming language", "I enjoy solving problems with Python"]   

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(document)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['enjoy' 'great' 'in' 'is' 'language' 'love' 'problems' 'programming'
 'python' 'solving' 'with']
[[0.         0.         0.5844829  0.         0.         0.5844829
  0.         0.44451431 0.34520502 0.         0.        ]
 [0.         0.50461134 0.         0.50461134 0.50461134 0.
  0.         0.38376993 0.29803159 0.         0.        ]
 [0.47952794 0.         0.         0.         0.         0.
  0.47952794 0.         0.28321692 0.47952794 0.47952794]]